### ISSUE TITLE
cannot reset the other visualizations depenedent on the text filter

### ISSUE THREAD

**Issue by shreyanshmohnot** [Microsoft/PowerBI-visuals-TextFilter#5] opened 2018-07-05 15:00 UTC
After inserting the text values in the search filter, it filters values correctly in all visualizations but after clearing the text filter, it does not reset the visualizations. They stay with the same filtered values. It just clears whats written in the filter. How can I able to reset the filter?

**Comment by katua** [comment] 2018-07-09 17:57
Thank you for reporting the issue. The issue should be fixed in the July version of Power BI Desktop. It will be released at the end of the month. Please, let us know if you still see it after update.

**Comment by katua** [comment] 2018-08-28 19:57
The issue is fixed in the latest build of PBI.

**Closed by katua** 2018-08-28 19:57 UTC
